package com.universidadeuropea.comia.model;

import lombok.Data;

@Data
public class NutritionalValues {
    private Integer minCarbs;
    private Integer maxCarbs;
    private Integer minProtein;
    private Integer maxProtein;
    private Integer minCalories;
    private Integer maxCalories;
    private Integer minFat;
    private Integer maxFat;
    private Integer minAlcohol;
    private Integer maxAlcohol;
    private Integer minCaffeine;
    private Integer maxCaffeine;
    private Integer minCopper;
    private Integer maxCopper;
    private Integer minCalcium;
    private Integer maxCalcium;
    private Integer minCholine;
    private Integer maxCholine;
    private Integer minCholesterol;
    private Integer maxCholesterol;
    private Integer minFluoride;
    private Integer maxFluoride;
    private Integer minSaturatedFat;
    private Integer maxSaturatedFat;
    private Integer minVitaminA;
    private Integer maxVitaminA;
    private Integer minVitaminC;
    private Integer maxVitaminC;
    private Integer minVitaminD;
    private Integer maxVitaminD;
    private Integer minVitaminE;
    private Integer maxVitaminE;
    private Integer minVitaminK;
    private Integer maxVitaminK;
    private Integer minVitaminB1;
    private Integer maxVitaminB1;
    private Integer minVitaminB2;
    private Integer maxVitaminB2;
    private Integer minVitaminB5;
    private Integer maxVitaminB5;
    private Integer minVitaminB3;
    private Integer maxVitaminB3;
    private Integer minVitaminB6;
    private Integer maxVitaminB6;
    private Integer minVitaminB12;
    private Integer maxVitaminB12;
    private Integer minFiber;
    private Integer maxFiber;
    private Integer minFolate;
    private Integer maxFolate;
    private Integer minFolicAcid;
    private Integer maxFolicAcid;
    private Integer minIodine;
    private Integer maxIodine;
    private Integer minIron;
    private Integer maxIron;
    private Integer minMagnesium;
    private Integer maxMagnesium;
    private Integer minManganese;
    private Integer maxManganese;
    private Integer minPhosphorus;
    private Integer maxPhosphorus;
    private Integer minPotassium;
    private Integer maxPotassium;
    private Integer minSelenium;
    private Integer maxSelenium;
    private Integer minSodium;
    private Integer maxSodium;
    private Integer minSugar;
    private Integer maxSugar;
    private Integer minZinc;
    private Integer maxZinc;

}
